
const cities = [

    'Comarca de Santiago',
    'Comarca de Ferrol',
    'Los Llanos de Albacete',
    'Mancha Júcar-Centro',
    'La Mancha',
    'Campo de Montiel',
    'Vega Baja del Segura',
    'Medio Vinalopó',
    'Marina Alta',
    'Alt Vinalopó',
    'Poniente Almeriense',
    'Comarca Metropolitana de Almería',
    'Levante Almeriense',
    'Comarca metropolitana de Almería',
    'Valle del Almanzora',
    'Costa de Almería',
    'Aiaraldea',
    'Tierra de Mérida - Vegas Bajas',
    'Zafra - Río Bodión',
    'Raiguer',
    'Mallorca',
    'Vallès Occidental',
    'Barcelonès',
    'Garraf',
    'Berguedà',
    'Baix Llobregat',
    'Vallès Oriental',
    'Osona',
    'Alt Penedès',
    'Anoia',
    'Bages',
    'Maresme',
    'Ribera del Duero',
    'Alfoz de Burgos',
    'Trasmiera',
    'Costa oriental',
    'Plana Baja',
    'Mancha Alta',
    'La Manchuela Conquense',
    'Miajadas-Trujillo',
    'Campo Arañuelo',
    'Costa Noroeste de Cádiz',
    'La Janda',
    'Campiña de Jerez',
    'Bahía de Cádiz',
    'Campo de Gibraltar',
    'Debabarrena',
    'Gironès',
    'Alto Ampurdán',
    'Baix Empordà',
    'La Selva',
    'Garrotxa',
    'Vega de Granada',
    'Costa Granadina',
    'Serranía de Guadalajara',
    'Campiña de Guadalajara',
    'Cuenca Minera',
    'Sierra de Huelva',
    'Costa Occidental',
    'Condado de Huelva',
    'Monegros',
    'Alto Galligo',
    'Cinca Medio',
    'Sobrarbe',
    'Comarca Metropolitana de Jaén',
    'Gran Canaria',
    'Comarca de La Cabrera',
    'Tierra de León',
    'Urgell',
    'A Mariña',
    'Mariña Occidental',
    'Corredor del Henares',
    'La Alcarria',
    'Cuenca del Medio Jarama',
    'Noroeste de Madrid',
    'Área Metropolitana de Madrid',
    'Valle del Lozoya',
    'Cuenca Alta del Manzanares',
    'Cuenca Alta del Manzanares',
    'Cuenca del Guadarrama',
    'La Encina',
    'Sierra Oeste de Madrid',
    'Alberche-Tiétar',
    'Cuenca del Henares',
    'Comarca de Las Vegas',
    'Sierra Norte',
    'Área metropolitana de Madrid',
    'Comarca de Alcalá',
    'La Axarquía',
    'Costa del Sol Occidental',
    'Costa del Sol',
    'Valdeorras',
    'Montaña Palentina',
    'Campo de Argañán',
    'Sierra de Béjar',
    'Comarca Metropolitana de Sevilla',
    'Tierras Altas',
    'Baix Ebre',
    'Alt Camp',
    `Terres de l'Ebre`,
    'Baix Penedès',
    'Bajo Aragón',
    'Mesa de Ocaña',
    'Campiña del Pisuerga',
    'Comarca de Valencia',
    'Horta Sud',
    'La Costera',
    `L'Horta Oest`,
    'Ribera Alta',
    'Zinco Billas',
    'Alto Tormes',
    'Valle del Tiétar',
]

export {cities};